class CreateUlapps < ActiveRecord::Migration
  def change
    create_table :ulapps do |t|
      t.string :application_status, default: "Unprocessed"
      t.string :credit_type
      t.text :joint_applicant
      t.string :amount
      t.text :purpose
      t.string :first_name
      t.string :last_name
      t.date :dob
      t.string :ssn
      t.string :sfcu_account
      t.string :name_relative
      t.string :phone_relative
      t.string :mothers
      t.date :graduation
      t.string :local_address_line1
      t.string :local_address_line2
      t.string :local_address_city
      t.string :local_address_state
      t.string :local_address_zip
      t.string :local_country
      t.string :perm_address_line1
      t.string :perm_address_line2
      t.string :perm_address_city
      t.string :perm_address_state
      t.string :perm_address_zip
      t.string :perm_country
      t.string :e_mail
      t.string :phone_number
      t.string :phone_type
      t.string :alter_number
      t.string :alter_type
      t.string :employer
      t.string :employee_address_line1
      t.string :employee_address_line2
      t.string :employee_address_city
      t.string :employee_address_state
      t.string :employee_address_zip
      t.string :employee_country
      t.string :position
      t.string :supervisor_firstname
      t.string :supervisor_lastname
      t.string :grosspay
      t.string :disbursement
      t.date :startingdate
      t.boolean :continue
      t.text :no
      t.text :additional
      t.string :employer2
      t.string :employee2_address_line1
      t.string :employee2_address_line2
      t.string :employee2_address_city
      t.string :employee2_address_state
      t.string :employee2_address_zip
      t.string :employee2_country
      t.string :position2
      t.string :supervisor2_firstname
      t.string :supervisor2_lastname
      t.string :grosspay2
      t.string :disbursement2
      t.date :startingdate2
      t.boolean :continue2
      t.text :no2
      t.string :source1
      t.string :amount1
      t.string :source2
      t.string :amount2
      t.string :source3
      t.string :amount3
      t.string :depository1
      t.string :account_type1
      t.string :balance1
      t.string :depository2
      t.string :account_type2
      t.string :balance2
      t.string :depository3
      t.string :account_type3
      t.string :balance3
      t.string :addr1
      t.string :market_value1
      t.string :pledged1
      t.string :addr2
      t.string :market_value2
      t.string :pledged2
      t.string :addr3
      t.string :market_value3
      t.string :pledged3
      t.string :creditor1
      t.string :cbalance1
      t.date :nextpayment1
      t.string :avg1
      t.boolean :pastdue1
      t.string :creditor2
      t.string :cbalance2
      t.date :nextpayment2
      t.string :avg2
      t.boolean :pastdue2
      t.string :creditor3
      t.string :cbalance3
      t.date :nextpayment3
      t.string :avg3
      t.boolean :pastdue3
      t.string :creditor4
      t.string :cbalance4
      t.date :nextpayment4
      t.string :avg4
      t.boolean :pastdue4
      t.string :loan_creditor1
      t.string :creditor_type1
      t.date :first_payment1
      t.date :last_payment1
      t.string :monthly1
      t.boolean :past_due1
      t.string :loan_creditor2
      t.string :creditor_type2
      t.date :first_payment2
      t.date :last_payment2
      t.string :monthly2
      t.boolean :past_due2
      t.text :expenses
      t.string :file1
      t.string :file2
      t.string :file3
      t.string :file4
      t.string :file5
      t.string :file6
      t.boolean :yesorno
      t.string :signature

      t.timestamps
    end
  end
end
