class CreateAlapps < ActiveRecord::Migration
  def change
    create_table :alapps do |t|
      t.string :first
      t.string :middle
      t.string :last
      t.date :dob
      t.string :mother_maiden
      t.string :ssn
      t.boolean :alumni
      t.string :credit_req_type
      t.float :amount_req
      t.string :term
      t.string :vehicle_condition
      t.float :price_range_min
      t.float :price_range_max
      t.integer :model_year
      t.boolean :veh_subcompact
      t.boolean :veh_compact
      t.boolean :veh_mid_size
      t.boolean :veh_full_size
      t.boolean :veh_sports_car
      t.boolean :veh_truck
      t.boolean :veh_van
      t.string :local_address_line1
      t.string :local_address_line2
      t.string :local_address_city
      t.string :local_address_state
      t.string :local_address_zip
      t.integer :local_country
      t.string :perm_address_line1
      t.string :perm_address_line2
      t.string :perm_address_city
      t.string :perm_address_state
      t.string :perm_address_zip
      t.string :perm_country
      t.string :e_mail
      t.string :phone_number
      t.string :name_nearest_relative
      t.string :phone_nearest_relative
      t.string :driver_lisence_num
      t.string :driver_license_file
      t.string :employ1_employer
      t.string :employ1_employer_addr
      t.string :employ1_position
      t.string :employ1_supervisor
      t.float :employ1_grosspay
      t.string :employ1_freq
      t.boolean :employ1_continue
      t.string :employ1_expect_duration
      t.string :employ2_employer
      t.string :employ2_employer_addr
      t.string :employ2_position
      t.string :employ2_supervisor
      t.float :employ2_grosspay
      t.string :employ2_freq
      t.boolean :employ2_continue
      t.string :employ2_expect_duration
      t.string :add_income1_source
      t.float :add_income1_amount
      t.string :add_income1_freq
      t.string :add_income2_source
      t.float :add_income2_amount
      t.string :add_income2_freq
      t.string :add_income3_source
      t.float :add_income3_amount
      t.string :add_income3_freq
      t.string :account1_depository
      t.string :account1_type
      t.float :account1_current_balance
      t.string :account2_depository
      t.string :account2_type
      t.float :account2_current_balance
      t.string :account3_depository
      t.string :account3_type
      t.float :account3_current_balance
      t.string :account4_depository
      t.string :account4_type
      t.float :account4_current_balance
      t.string :property1_st_addr
      t.string :property1_city
      t.string :property1_state
      t.float :property1_market_val
      t.boolean :property1_another_loan
      t.string :property2_st_addr
      t.string :property2_city
      t.string :property2_state
      t.float :property2_market_val
      t.boolean :property2_another_loan
      t.string :credit_card1_name
      t.float :credit_card1_limit
      t.float :credit_card1_balance
      t.date :credit_card1_date_payment
      t.float :credit_card1_aveg_month_pay
      t.boolean :credit_card1_pastdue
      t.string :credit_card2_name
      t.float :credit_card2_limit
      t.float :credit_card2_balance
      t.date :credit_card2_date_payment
      t.float :credit_card2_aveg_month_pay
      t.boolean :credit_card2_pastdue
      t.string :credit_card3_name
      t.float :credit_card3_limit
      t.float :credit_card3_balance
      t.date :credit_card3_date_payment
      t.float :credit_card3_aveg_month_pay
      t.boolean :credit_card3_pastdue
      t.string :credit_card4_name
      t.float :credit_card4_limit
      t.float :credit_card4_balance
      t.date :credit_card4_date_payment
      t.float :credit_card4_aveg_month_pay
      t.boolean :credit_card4_pastdue
      t.string :loan1_name
      t.string :loan1_type
      t.float :loan1_principal
      t.date :loan1_date_payment
      t.float :loan1_month_payment
      t.boolean :loan1_pastdue
      t.string :loan2_name
      t.string :loan2_type
      t.float :loan2_principal
      t.date :loan2_date_payment
      t.float :loan2_month_payment
      t.boolean :loan2_pastdue
      t.string :loan3_name
      t.string :loan3_type
      t.float :loan3_principal
      t.date :loan3_date_payment
      t.float :loan3_month_payment
      t.boolean :loan3_pastdue
      t.string :loan4_name
      t.string :loan4_type
      t.float :loan4_principal
      t.date :loan4_date_payment
      t.float :loan4_month_payment
      t.boolean :loan4_pastdue
      t.float :rent_housing
      t.string :rent_person
      t.float :food
      t.string :food_person
      t.float :utilities
      t.string :utilities_person
      t.float :phone_bill
      t.string :phone_bill_person
      t.float :bursar_bill
      t.float :miscellaneous
      t.string :miscellaneous_expl
      t.string :document1
      t.string :document2
      t.string :document3
      t.string :document4
      t.string :document5
      #t.boolean :agree_terms
      t.string :signature
      t.date :today_date

      t.timestamps
    end
  end
end
